dataset:
    train_path: ./train
    val_path: ./val
    train_preprocessing_config: ./conf/train_preprocessing.yaml
    val_preprocessing_config: ./conf/val_preprocessing.yaml
    loader_num_workers: 2
    test_size: 0.2
    batch_size: 8
